---
title: "DataViz 2020/1 - Data Science Courses in Berkeley"
author: "Ijeamaka Anyene"
date: "1/28/2020"
output: html_document
---

```{r prep, message = FALSE}
library(dplyr)
library(stringr)
library(ggplot2)
library(patchwork)
```

```{r data}
paths = here::here("data", "Courses_Berkeley_2018-01-15.csv")

# Data obtained from: https://uccliometric.org/courses/
berkeley = readr::read_csv(paths, 
                           col_types = c("dcccccciilllll"))
```

```{r prep}
berkeley_prep = berkeley %>%
  mutate(ds_name = str_detect(Name, 
                          "(D|d)ata\\s*(S|s)cience|(D|d)ata\\s*(A|a)naly(sis|tics)|(M|m)achine\\s*(L|l)earning|(D|d)ata\\s*(M|m)ining"),
         ds_desc = str_detect(Description,              
                          "(D|d)ata\\s*(S|s)cience|(D|d)ata\\s*(A|a)naly(sis|tics)|(M|m)achine\\s*(L|l)earning|(D|d)ata\\s*(M|m)ining"),
         overall_name_t = str_detect(Name,
                                     "(S|s)tatistical\\s*(L|l)earning|(S|s)tatistical\\s*(C|c)omput(ing|ation)|(C|c)omputing|(D|d)ata"),
         overall_desc_t = str_detect(Description,
                                     "(S|s)tatistical\\s*(L|l)earning|(S|s)tatistical\\s*(C|c)omput(ing|ation)|(C|c)omputing")) %>%
  mutate(overall_name = if_else(ds_name == TRUE | overall_name_t == TRUE, TRUE, FALSE),
         overall_desc = if_else(ds_desc == TRUE | overall_desc_t == TRUE, TRUE, FALSE)) %>%
  mutate(data_science = if_else(ds_name == TRUE | ds_desc == TRUE, TRUE, FALSE),
         overall = if_else(overall_name == TRUE | overall_desc == TRUE, TRUE, FALSE))
```

```{r counts}
counts_berkeley = berkeley_prep %>%
  select(Year, Field, Name, Area, GenArea, data_science, overall) %>%
  filter(data_science == TRUE) %>%
  group_by(Year, GenArea) %>%
  count(name = "num_classes") %>%
  ungroup() %>%
  tidyr::spread(key = GenArea, value = num_classes, fill = 0) %>%
  tidyr::gather(key = GenArea, value = num_classes, -Year) %>%
  arrange(Year, GenArea)
```

```{r plots1}
plot_counts = counts_berkeley %>%
  group_by(Year) %>%
  summarise(sum_classes = sum(num_classes)) %>%
  ggplot(., aes(x = Year, y = sum_classes)) +
  geom_area(fill = "#b3cde0") + 
  labs(y = "Number of Classes") +
  theme_minimal(base_size = 18) +
  theme(axis.title.x = element_blank())
```

```{r plots 2}
plot_counts_2 = counts_berkeley %>%
  group_by(Year, GenArea) %>%
  summarise(sum_classes = sum(num_classes)) %>%
  ggplot(., aes(x = Year, y = sum_classes)) +
  geom_area(aes(colour = GenArea, fill = GenArea)) +
  labs(colour = "Department's General\n Area of Study", 
       fill = "Department's General\n Area of Study") +
  theme_minimal(base_size = 18) + 
  theme(axis.title.x = element_blank(), 
        axis.title.y =  element_blank(),
        legend.title = element_text(size = 11),
        legend.text = element_text(size = 9),
        legend.justification = "top")

plot_counts_2

```

```{r title}
title = ggplot(data.frame(x = 1:2, y = 1:10)) +
  labs(x = NULL, y = NULL,
       title = "Data Science Courses Offered at U.C. Berkeley, 1963 - 2011",
       subtitle = paste0("The number of data science courses offered has unsurprisingly experienced a major growth over the past few decades,\n", "but what may surprise you are the departments driving this growth")) +
  theme_minimal(base_size = 18) + 
  theme(line = element_blank(),
        plot.background = element_rect(fill = "transparent", color = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(color = "transparent"),
        axis.text = element_blank())
  
```

```{r}
caption = ggplot(data.frame(x = 1:20, y = 1:20)) +
  labs(x = NULL, y = NULL,
       caption = paste0("Source: UC ClioMetric History Project\n",
                     "Visualization: Ijeamaka Anyene")) +
  theme_minimal(base_size = 12) + 
  theme(line = element_blank(),
        plot.background = element_rect(fill = "transparent", color = "transparent"),
        panel.background = element_rect(fill = "transparent"),
        panel.border = element_rect(color = "transparent"),
        axis.text = element_blank())

```

```{r full-panel, fig.width = 14, fig.height = 5.5}
title + plot_counts + plot_counts_2 + caption + plot_layout(widths = c(0, 1, 1, 0), nrow = 1)

ggsave(here::here("outputs", "2020-01_berkeleycourses.png"), 
       width = 14, height = 5.6)
```