---
title: "plants_in_danger"
author: "Ijeamaka Anyene"
date: "8/17/2020"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(ggimage)
library(ggtext)
```

```{r, message = FALSE}
extrafont::loadfonts()
```

```{r}
plants = readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-08-18/plants.csv')
```

```{r}
extinct_plants = 
  plants %>%
  filter(red_list_category == "Extinct" & continent == "Africa") %>%
  #mutate(year = case_when(
   # year_last_seen == "Before 1900" ~ "1900",
    #year_last_seen != "Before 1900" ~ stringr::str_sub(year_last_seen, 1, 4))) %>%
  select(binomial_name, country, continent, year_last_seen) %>%
  mutate(binomial_name = case_when(
    binomial_name == "Schizenterospermum analamerense" ~ "Schizenterospermum \nanalamerense",
    TRUE ~ binomial_name)) %>%
  mutate(year_tl = case_when(
    year_last_seen == "Before 1900" ~ 0,
    year_last_seen == "1900-1919" ~ 15,
    year_last_seen == "1920-1939" ~ 30,
    year_last_seen == "1940-1959" ~ 45,
    year_last_seen == "1960-1979" ~ 60,
    year_last_seen == "1980-1999" ~ 75,
    year_last_seen == "2000-2020" ~ 90
  )) %>%
  arrange(year_tl)
```

```{r}
counts_year = extinct_plants %>%
  count(year_tl) %>%
  select(n) %>%
  unname() %>%
  unlist()
```

```{r}
extinct_plants =
  extinct_plants %>%
  mutate(counts_year = c(seq(1, counts_year[1]),
                         seq(1, counts_year[2]),
                         seq(1, counts_year[3]),
                         seq(1, counts_year[4]),
                         seq(1, counts_year[5]),
                         seq(1, counts_year[6]),
                         seq(1, counts_year[7]),
                         seq(1, counts_year[8])),
         counts_year = -counts_year) %>%
  filter(year_tl != "NA")
```

```{r}
african_regions = tibble(
  country = unique(extinct_plants$country),
  region = c("West", "East", "East", "Southern", "East",
             "Central", "West", "Central", "West", "West",
             "Northern", "East", "East", "Southern", "Central",
             "East", "Central", "East", "East", "Southern", "Southern",
             "Southern"))

```

```{r}
extinct_plants = left_join(extinct_plants, african_regions, by = c("country" = "country"))
```


```{r}
#https://www.color-hex.com/color-palette/79518
region_palette = c("#b84d2b", "#076733","#fcd0ac", 
                   "#08705f", "#ffdc33")

```

```{r}
legend = tibble(
  x = rep(4, 5), 
  y = seq(-47, -51, by = -1),
  region = c("Central", "East", "Northern", "Southern", "West")
)
```

```{r}
# Plant by Alex Muravev from the Noun Project
plant_img = c(here::here("data", "plants_in_danger", "noun_plant.png"))
```

```{r}
ggplot() +
  # Extinct plants names
  geom_text(data = extinct_plants,
            aes(x = year_tl, y = counts_year, label = binomial_name),
            hjust = 0, fontface = "italic", family = "Lora") +
  geom_point(data = extinct_plants,
             aes(x = (year_tl - 0.5), y = counts_year, color = region),
             size = 2) +
  # Timeline
  geom_point(data = extinct_plants,
             aes(x = year_tl + 2, y = 1), 
             size = 10, colour = "#670000", alpha = 1/100) +
  geom_image(data = extinct_plants,
             aes(x = year_tl, y = 1, image = plant_img), size = 0.05) +
  geom_text(data = extinct_plants,
            aes(x = year_tl + 4.5, y = 1, label = year_last_seen),
            fontface = "bold", family = "Lora") +
  # Legend
  geom_point(data = legend,
             aes(x = x, y = y, colour = region),
             size = 6) +
  geom_text(data = legend,
            aes(x = x + 3, y = y, label = region),
            family = "Lora", size = 6, hjust = 0) +
  geom_text(aes(x = 4, y = -45, label = "African Regions"),
            family = "Lora", fontface = "bold", size = 7, hjust = 0) +
  
  labs(title = "\nExtinct Plants",
       subtitle = "Africa",
       caption = paste0("Source: IUCN | Plant Icon by Alex Muravev @ Noun Project | Visualization by @ijeamaka_a")) +
  scale_color_manual(values = region_palette) +
  xlim(-2, 100) +
  theme(
    panel.background = element_rect(fill = "#dfdacd"),
    plot.background = element_rect(fill = "#dfdacd"),
    panel.grid = element_blank(),
    plot.title = element_text(hjust = 0.5, family = "Lora",
                                  face = "bold", size = 50),
    plot.subtitle = element_text(hjust = 0.5, family = "Lora",
                                  face = "italic", size = 45),
    plot.caption = element_text(size = 10),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    legend.position = "none"
    )

```

```{r}
ggsave(filename = "2020-17_plants_in_danger.png", 
       plot = last_plot(), 
       device = "png",
       type = "cairo",
       path = here::here("outputs"), 
       width = 17, height = 17)
```




